name: hytracker
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.0
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/search.png
    - assets/images/edit.png
    - assets/images/bedwars.png
    - assets/images/skywars.png
    - assets/images/profile.png
    - assets/images/tracker.png
    - assets/images/history.png
    - assets/images/duels.png

  fonts: 
      - family: Minecraftia
        fonts:
          - asset: assets/fonts/MinecraftRegular.otf
          - asset: assets/fonts/MinecraftBold.otf
            weight: 700
